version: 0.1

environment_variables:
  plaintext:
    PATH: "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
phases:
  install:
    commands:
      - yum update -y
      - yum install autotools automake install -y util-linux rpm-build tree
  pre_build:
    commands:
      - mkdir /root/rpmbuild
      - echo -e "%_topdir /root/rpmbuild" > /root/.rpmmacros
  build:
    commands:
      - env
      - autoreconf -i --force
      - ./configure --prefix=/usr --with-perl5libdir --enable-rpmbuild --disable-perldeps
      - make dist
      - rpmbuild -tb $(ls -1 *.tar.gz | head -1)
      - test -e target-repo || echo "tbc-amzn-ami" > target-repo
      - cp target-repo "/root/repo/$(basename $(ls -1 *.tar.gz | head -1) .tar.gz).repo"
      - tree /root
artifacts:
  discard-paths: yes
  files:
    - /root/rpmbuild/RPMS/noarch/*
    - /root/repo/*
